apiVersion: v1
kind: Service
metadata:
  name: sample-api
  labels:
    app: sample-api
    release: stable
    environment: production
    tier: backend
spec:
  selector:
    app: sample-api
    release: stable
    environment: production
    tier: backend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  type: LoadBalancer
