apiVersion: v1
kind: Service
metadata:
  name: sample-api
  labels:
    app: sample-api
    release: stable
    environment: production
    tier: backend
spec:
  selector:
    app: sample-api
    release: stable
    environment: production
    tier: backend
  type: LoadBalancer
